// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package modals

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SyncDeviceModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"absolute top-0 left-0 w-full h-full bg-white/40 z-10 flex items-center justify-center\" data-show=\"$showSyncDeviceModal\" data-signals=\"{_syncDeviceModalFocusAbortController:new AbortController()}\"><dialog open class=\"w-11/12 mx-auto animate-modal shadow-2xl border border-gray-300 bg-light dark:bg-dark py-4 px-6 rounded flex flex-col md:w-7/12 lg:w-5/12 xl:w-4/12\" id=\"syncDeviceModal\" style=\"view-transition-name:sync-device-dialog\" data-effect=\"$showSyncDeviceModal?$_syncDeviceModalFocusAbortController=focusTrap('#syncDeviceModal'):$_syncDeviceModalFocusAbortController.abort()\"><h1 class=\"text-xl font-semibold dark:text-light\">Sync your chats across devices</h1><h2 class=\"mt-4 opacity-90 dark:text-light\">Connect another device to access your conversations.</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SyncDeviceModalDefaultActions().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</dialog></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SyncDeviceModalDefaultActions() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"mt-8 mb-4 flex items-center justify-end gap-2\" id=\"syncDeviceModalAction\"><button class=\"appearance-none outline-none transition duration-300 py-2 px-4 rounded cursor-pointer bg-dark dark:bg-light text-light dark:text-dark focus:ring-2 focus:ring-dark dark:focus:ring-light focus:ring-offset-2 focus:ring-offset-light dark:focus:ring-offset-dark disabled:cursor-not-allowed disabled:opacity-80\" data-on:click=\"@post('/sync/generate')\" data-indicator=\"_generatingSyncCode\" data-attr:disabled=\"$_generatingSyncCode\" data-text=\"$_generatingSyncCode?'Generating':'Generate a code'\">Generate a code</button> <button class=\"appearance-none outline-none transition duration-300 py-2 px-4 rounded cursor-pointer bg-dark dark:bg-light text-light dark:text-dark focus:ring-2 focus:ring-dark dark:focus:ring-light focus:ring-offset-2 focus:ring-offset-light dark:focus:ring-offset-dark disabled:cursor-not-allowed disabled:opacity-80\" data-on:click=\"@post('/sync/enter')\" data-indicator=\"_visitingEnterSyncCode\" data-attr:disabled=\"$_visitingEnterSyncCode\" data-text=\"$_visitingEnterSyncCode?'Loading...':'Enter a code'\">Enter a code</button> <button class=\"appearance-none outline-none transition duration-300 py-2 px-4 rounded cursor-pointer bg-dark dark:bg-light text-light dark:text-dark focus:ring-2 focus:ring-dark dark:focus:ring-light focus:ring-offset-2 focus:ring-offset-light dark:focus:ring-offset-dark disabled:cursor-not-allowed disabled:opacity-80\" data-on:click__viewtransition=\" $showSyncDeviceModal=false;\">Cancel</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SyncDeviceModalDisplayCode(value string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"mt-8 mb-4 flex flex-col gap-2\" id=\"syncDeviceModalAction\"><label class=\"text-xl dark:text-light\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(value)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/modals/syncDevice.templ`, Line: 50, Col: 18}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</label><div class=\"mb-4 flex items-center justify-end gap-2\"><button class=\"appearance-none outline-none transition duration-300 py-2 px-4 rounded cursor-pointer bg-dark dark:bg-light text-light dark:text-dark focus:ring-2 focus:ring-dark dark:focus:ring-light focus:ring-offset-2 focus:ring-offset-light dark:focus:ring-offset-dark disabled:cursor-not-allowed disabled:opacity-80\" data-on:click__viewtransition=\" $showSyncDeviceModal=false;\">Cancel</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SyncDeviceModalEnterCode() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<form class=\"mt-8 flex flex-col gap-3\" id=\"syncDeviceModalAction\" data-on:submit__prevent=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(`
                    if(!$_syncing){ 
                        @post('/sync/verify');
                    }
                `)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/modals/syncDevice.templ`, Line: 67, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" data-indicator=\"_syncing\"><label class=\"text-lg flex flex-col gap-2 dark:text-light\" for=\"txtSyncCode\">Enter the code from your other device <input class=\"appearance-none outline-none cursor-pointer py-2 px-4 rounded transition duration-300 border border-dark dark:border-light bg-light dark:bg-dark text-dark dark:text-light focus:ring-2 focus:ring-offset-2 focus:ring-dark dark:focus:ring-light focus:ring-offset-light dark:focus:ring-offset-dark disabled:cursor-not-allowed disabled:opacity-80\" id=\"txtSyncCode\" required type=\"text\" minlength=\"6\" name=\"syncCode\" data-bind=\"syncCode\"></label><div class=\"mb-4 flex items-center justify-end gap-2\"><button class=\"appearance-none outline-none transition duration-300 py-2 px-4 rounded cursor-pointer bg-dark dark:bg-light text-light dark:text-dark focus:ring-2 focus:ring-dark dark:focus:ring-light focus:ring-offset-2 focus:ring-offset-light dark:focus:ring-offset-dark disabled:cursor-not-allowed disabled:opacity-80\" type=\"submit\" data-attr:disabled=\"$_syncing\" data-text=\"$_syncing?'Syncing...':'Submit'\">Submit</button> <button class=\"appearance-none outline-none transition duration-300 py-2 px-4 rounded cursor-pointer bg-dark dark:bg-light text-light dark:text-dark focus:ring-2 focus:ring-dark dark:focus:ring-light focus:ring-offset-2 focus:ring-offset-light dark:focus:ring-offset-dark disabled:cursor-not-allowed disabled:opacity-80\" type=\"button\" data-on:click__viewtransition=\" $showSyncDeviceModal=false;\">Cancel</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
